server:
  port: 8080
  context-path: /auth_server

security:
  user:
    password: admin
    name: user
  basic:
    enabled: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot?useSSL=false
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver

